"use client";

import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from "@react-pdf/renderer";
import { Download } from "lucide-react";
import { useEffect, useState } from "react";

// --- Types ---
export interface PDFResultItem {
    label: string;
    value: string;
    subtext?: string;
}

interface DownloadPDFButtonProps {
    fileName: string;
    title: string;
    /**
     * Array of data points to display in the PDF.
     * Replaces the old DOM scraping method.
     */
    data?: PDFResultItem[];
    /**
     * @deprecated The DOM scraping method (html2canvas) is removed due to incompatibilities with modern CSS.
     * This prop is kept locally to avoid immediate build errors in parent components, but it is ignored.
     */
    targetId?: string;
}

// --- Styles ---
const styles = StyleSheet.create({
    page: {
        flexDirection: "column",
        backgroundColor: "#FAF7EE",
        padding: 40,
        fontFamily: "Helvetica",
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderBottomWidth: 2,
        borderBottomColor: "#31372B",
        paddingBottom: 20,
        marginBottom: 30,
    },
    headerLeft: {
        flexDirection: "column",
    },
    title: {
        fontSize: 24,
        fontWeight: "bold", // Helvetica-Bold
        color: "#31372B",
    },
    subtitle: {
        fontSize: 10,
        color: "#717182",
        marginTop: 4,
    },
    brand: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#31372B",
    },
    contentCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        padding: 20,
        borderWidth: 1,
        borderColor: "#E5E5E5",
    },
    row: {
        flexDirection: "column", // Stack vertically for mobile-like feel or items
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f3f4f6",
    },
    lastRow: {
        marginBottom: 0,
        paddingBottom: 0,
        borderBottomWidth: 0,
    },
    label: {
        fontSize: 10,
        color: "#717182",
        marginBottom: 4,
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    value: {
        fontSize: 18,
        color: "#31372B",
        fontWeight: "bold",
    },
    subtext: {
        fontSize: 10,
        color: "#717182",
        marginTop: 2,
        fontStyle: "italic",
    },
    footer: {
        position: "absolute",
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: "center",
        borderTopWidth: 1,
        borderTopColor: "#CCCCCC",
        paddingTop: 10,
    },
    footerText: {
        fontSize: 10,
        color: "#717182",
    },
});

// --- PDF Document Component ---
const ResultsDocument = ({ title, data = [] }: { title: string; data: PDFResultItem[] }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header */}
            <View style={styles.header}>
                <View style={styles.headerLeft}>
                    <Text style={styles.title}>{title}</Text>
                    <Text style={styles.subtitle}>Generated by MyFundingList</Text>
                </View>
                <View>
                    <Text style={styles.brand}>MyFundingList</Text>
                </View>
            </View>

            {/* Content */}
            <View style={styles.contentCard}>
                {data.map((item, index) => (
                    <View key={index} style={[styles.row, index === data.length - 1 ? styles.lastRow : {}]}>
                        <Text style={styles.label}>{item.label}</Text>
                        <Text style={styles.value}>{item.value}</Text>
                        {item.subtext && <Text style={styles.subtext}>{item.subtext}</Text>}
                    </View>
                ))}
            </View>

            {/* Footer */}
            <View style={styles.footer}>
                <Text style={styles.footerText}>
                    Calculated on {new Date().toLocaleDateString()} at MyFundingList.com
                </Text>
            </View>
        </Page>
    </Document>
);

// --- Main Button Component ---
export default function DownloadPDFButton({ fileName, title, data = [] }: DownloadPDFButtonProps) {
    const [isClient, setIsClient] = useState(false);

    useEffect(() => {
        setIsClient(true);
    }, []);

    // We can't render PDFDownloadLink on server
    if (!isClient) return null;

    // Use fileName as default filename
    const actualFileName = fileName.endsWith(".pdf") ? fileName : `${fileName}.pdf`;

    return (
        <PDFDownloadLink
            document={<ResultsDocument title={title} data={data} />}
            fileName={actualFileName}
            className="flex items-center gap-2 text-sm font-medium text-[#31372B] hover:text-[#717182] transition disabled:opacity-50"
            style={{ textDecoration: "none" }}
        >
            {({ loading }) => (
                <>
                    <Download className="w-4 h-4" />
                    {loading ? "Preparing..." : "Download"}
                </>
            )}
        </PDFDownloadLink>
    );
}
